apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/configmap.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml
  - backend/pdb.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/pdb.yaml
  - ingress/ingress.yaml
