apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: claude-gateway-staging

resources:
  - namespace.yaml
  - ../../base

configMapGenerator:
  - name: backend-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=staging
      - APP_FRONTEND_URL=https://portal.ng-itconsulting.com
      - AWS_TEXTRACT_REGION=eu-west-3

patches:
  - path: service-account-patch.yaml
    target:
      kind: ServiceAccount
      name: claude-gateway-backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: claude-gateway-backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: claude-gateway-frontend

commonLabels:
  environment: staging
